-- MySQL Script generated by MySQL Workbench
-- Mon Aug 17 20:56:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDSERVICIOPROGRA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDSERVICIOPROGRA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDSERVICIOPROGRA` DEFAULT CHARACTER SET utf8 ;
USE `BDSERVICIOPROGRA` ;

-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Cliente` (
  `dniClie` CHAR(8) NOT NULL,
  `nombClie` VARCHAR(25) NOT NULL,
  `apelClie` VARCHAR(25) NOT NULL,
  `celuClie` CHAR(10) NOT NULL,
  PRIMARY KEY (`dniClie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Plan` (
  `idPlan` CHAR(20) NOT NULL,
  `costPan` DECIMAL(5,2) NOT NULL,
  `minutDestPlan` CHAR(15) NOT NULL,
  `BMPlan` CHAR(10) NOT NULL,
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Servicio` (
  `numeServ` CHAR(5) NOT NULL,
  `fechInicServ` DATE NOT NULL,
  `fechPagoServ` DATE NOT NULL,
  `idPlan` CHAR(20) NOT NULL,
  PRIMARY KEY (`numeServ`),
  INDEX `fk_Servicio_Plan1_idx` (`idPlan` ASC),
  CONSTRAINT `fk_Servicio_Plan1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `BDSERVICIOPROGRA`.`Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Cliente_Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Cliente_Servicio` (
  `dniClie` CHAR(8) NOT NULL,
  `FechaPago` DATE NULL,
  `pago` DECIMAL(5,2) NULL,
  `numeServ` CHAR(5) NOT NULL,
  PRIMARY KEY (`dniClie`, `numeServ`),
  INDEX `fk_Cliente_has_Servicio_Cliente1_idx` (`dniClie` ASC),
  INDEX `fk_Cliente_Servicio_Servicio1_idx` (`numeServ` ASC),
  CONSTRAINT `fk_Cliente_has_Servicio_Cliente1`
    FOREIGN KEY (`dniClie`)
    REFERENCES `BDSERVICIOPROGRA`.`Cliente` (`dniClie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Servicio_Servicio1`
    FOREIGN KEY (`numeServ`)
    REFERENCES `BDSERVICIOPROGRA`.`Servicio` (`numeServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Informe` (
  `id` CHAR(10) NOT NULL,
  `FechaPago` DATE NOT NULL,
  `pago` DECIMAL(5,2) NOT NULL,
  `dniClie` CHAR(8) NOT NULL,
  `idPlan` CHAR(20) NOT NULL,
  `numeServ` CHAR(5) NOT NULL,
  INDEX `fk_Informe_Cliente1_idx` (`dniClie` ASC),
  INDEX `fk_Informe_Plan1_idx` (`idPlan` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Informe_Servicio1_idx` (`numeServ` ASC),
  CONSTRAINT `fk_Informe_Cliente1`
    FOREIGN KEY (`dniClie`)
    REFERENCES `BDSERVICIOPROGRA`.`Cliente` (`dniClie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Informe_Plan1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `BDSERVICIOPROGRA`.`Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Informe_Servicio1`
    FOREIGN KEY (`numeServ`)
    REFERENCES `BDSERVICIOPROGRA`.`Servicio` (`numeServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDSERVICIOPROGRA`.`Rol_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDSERVICIOPROGRA`.`Rol_Usuario` (
  `dni` CHAR(8) NOT NULL,
  `rol` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `contrasena` VARCHAR(65) NOT NULL,
  `telefono` CHAR(9) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
